{{- if and .Values.bigbangPreflight.enabled .Values.bigbangPreflight.serviceAccount.create -}}

{{- $custom := dict "" "" }}
{{- $_ := set $custom "serviceAccountName" (include "bigbang-preflight.service-account-name" .) }}
{{- $_ := set $custom "labels" (include "bigbang-preflight.labels" .) }}
{{- $_ := set $custom "annotations" (include "bigbang-preflight.service-account-annotations" .) }}

{{- $args := dict "scope" . "custom" $custom }}

{{- include "bbctl.common.service-account" $args | nindent 0 }}
{{- end }}
