{{- if and .Values.bigbangUpdater.enabled .Values.bigbangUpdater.serviceAccount.create }}

{{- $custom := dict "" "" }}
{{- $_ := set $custom "serviceAccountName" (include "bigbang-updater.service-account-name" .) }}
{{- $_ := set $custom "labels" (include "bigbang-updater.labels" .) }}
{{- $_ := set $custom "annotations" (include "bigbang-updater.service-account-annotations" .) }}

{{- $args := dict "scope" . "custom" $custom }}

{{- include "bbctl.common.cluster-admin-cluster-role-binding" $args | nindent 0 }}
{{- end }}

